export const coffeesJson = [
    {id:1, name:'Expresso Tradicional', img:'Image.svg', price:9.90, model:['tradicional'], description:'O tradicional café feito com água quente e grãos moídos'},
    {id:2, name:'Expresso Americano', img:'Image-2.svg', price:9.90, model:['tradicional'], description:'Expresso diluído, menos intenso que o tradicional'},
    {id:3, name:'Expresso Cremoso', img:'Image-3.svg', price:9.90, model:['tradicional'], description:'Café expresso tradicional com espuma cremosa'},
    {id:4, name:'Expresso Gelado', img:'Image-4.svg', price:9.90, model:['tradicional', 'gelado'], description:'Bebida preparada com café expresso e cubos de gelo'},
    {id:5, name:'Café com Leite', img:'Image-5.svg', price:9.90, model:['tradicional', 'com leite'], description:'Meio a meio de expresso tradicional com leite vaporizado'},
    {id:6, name:'Latte', img:'Image-6.svg', price:9.90, model:['tradicional', 'com leite'], description:'Uma dose de café expresso com o dobro de leite e espuma cremosa'},
    {id:7, name:'Capuccino', img:'Image-7.svg', price:9.90, model:['tradicional', 'com leite'], description:'Bebida com canela feita de doses iguais de café, leite e espuma'},
    {id:8, name:'Macchiato', img:'Image-8.svg', price:9.90, model:['tradicional', 'com leite'], description:'Café expresso misturado com um pouco de leite quente e espuma'},
    {id:9, name:'Mocaccino', img:'Image-9.svg', price:9.90, model:['tradicional', 'com leite'], description:'Café expresso com calda de chocolate, pouco leite e espuma'},
    {id:10, name:'Chocolate Quente', img:'Image-10.svg', price:9.90, model:['expecial', 'com leite'], description:'Bebida feita com chocolate dissolvido no leite quente e café'},
    {id:11, name:'Cubano', img:'Image-11.svg', price:9.90, model:['especial', 'alcoólico', 'gelado'], description:'Drink gelado de café expresso com rum, creme de leite e hortelã'},
    {id:12, name:'Havaiano', img:'Image-12.svg', price:9.90, model:['especial'], description:'Bebida adocicada preparada com café e leite de coco'},
    {id:13, name:'Árabe', img:'Image-13.svg', price:9.90, model:['especial'], description:'Bebida preparada com grãos de café árabe e especiarias'},
    {id:14, name:'Irlandês', img:'Image-14.svg', price:9.90, model:['especial', 'alcoólico'], description:'Bebida a base de café, uísque irlandês, açúcar e chantilly'},
];